### PR TITLE
docs: added swayidle integration section to readme

### PR DESCRIPTION
**Pull request by fritzrehde**
I thought adding what I learned from the #57 issue might be useful for new, inexperienced wayland users wanting to use waylock.

### CODE REVIEW

**Comment by Leon-Plickat** [comment]
Pointing out the existence of swayidle is a decent addition IMO, but how to configure it is out of scope for the waylock documentation and is already explained well and in detail in swayidles documentation. We should assume that users are capable of figuring things out themselves from there.

**Comment by fritzrehde** [comment]
I see your point. What do you think of removing the timeout part and only including `swayidle -w before-sleep "waylock -fork-on-lock"`? I think that would be quite useful.

**Comment by Leon-Plickat** [comment]
Instead of showing an example, pointing out what `-fork-on-lock` does and why it may be needed makes more sense. IMO reference docs are always worth more than specific guides, readers commonly feel more productive with the latter but actually learn more from the former.

**Comment by ifreund** [comment]
I've pushed a commit (43fb605f421fed81a292f92993391dfeb646a965) to mention swayidle for users that aren't aware of it.

**Pull request closed without merging**
